### ISSUE TITLE
Dead URL on Rothamsted's GitHub Profile

### ISSUE THREAD

**Issue by peterjc** [Rothamsted/rothamsted.github.io#3]
This isn't actually a bug on https://rothamsted.github.io/ which looks to be a place holder only for now, but it seemed the best place to log this issue.

https://github.com/Rothamsted has the logo, name Rothamsted Bioinformatics, and URL http://www.rothamsted.ac.uk/applied-bioinformatics

That URL currently gives Error 404, Page Not Found.

I would guess that https://www.rothamsted.ac.uk/computational-and-analytical-sciences would be a good alternative, and if so suggest in addition to changing this you ask the webmaster to setup a redirection link?

**Comment by KeywanHP** [comment]
The new Rothamsted website is currently missing group and cluster pages.

I've updated the link to the CAS department page for now...

Thanks @peterjc for pointing it out.
